name: build+test
on:
  schedule:
  - cron: "0 8 * * 2,4,6"
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build-images:
    strategy:
      matrix:
        version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    name: Build Python Docker images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: build ascii-animator ${{ matrix.version }} image
        run:
          docker image build --build-arg PYTHON_VERSION=${{ matrix.version }} -t ascii-animator:${{ matrix.version }} .
