name: build
on:
  schedule:
  - cron: "0 8 * * *"
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build-images:
    strategy:
      matrix:
        version: ['3.7', '3.8', '3.9', '3.10']
    name: Build Python Docker images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: build ascii-animator ${{ matrix.version }} image
        run:
          docker image build --build-arg PYTHON_VERSION=${{ matrix.version }} -t ascii-animator:${{ matrix.version }} .
      - name: save ascii-animator ${{ matrix.version }} image
        if: ${{ matrix.version == '3.9' }}
        run: |
          mkdir -p images
          docker save --output images/ascii-animator-${{ matrix.version }}.tar ascii-animator:${{ matrix.version }}
      - name: upload ascii-animator ${{ matrix.version }} image artifact
        if: ${{ matrix.version == '3.9' }}
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: images/ascii-animator-${{ matrix.version }}.tar
  coverage:
    name: Publish Code Coverage Report
    needs: build-images
    runs-on: ubuntu-20.04
    steps:
      - name: download image artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: images/
      - name: load image
        run:
          docker load --input images/ascii-animator-3.9.tar
      - name: prepare report
        run: |
          ID=$(docker create ascii-animator:3.9)
          docker cp $ID:/code/target/reports/ascii-animator_coverage.xml ascii-animator_coverage.xml
          sed -i -e 's,filename="ascii_animator/,filename="src/main/python/ascii_animator/,g' ascii-animator_coverage.xml
      - name: upload report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ascii-animator_coverage.xml